# Generated by Django 5.0.4 on 2024-05-19 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=1000)),
                ('user_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('artist_id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=1000)),
                ('country', models.CharField(max_length=1000)),
                ('artist_image', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('genre_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfor',
            fields=[
                ('user_id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=1000)),
                ('avatar_image', models.TextField()),
                ('playlist_ids', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=10000)),
                ('track_url', models.TextField()),
                ('image_url', models.TextField()),
                ('duration', models.IntegerField()),
                ('release_year', models.IntegerField()),
                ('view', models.IntegerField()),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.artist')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.genre')),
            ],
        ),
    ]
