# Generated by Django 5.0.4 on 2024-05-20 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('playlist_id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('playlist_name', models.CharField(max_length=1000)),
                ('track_ids', models.TextField()),
                ('recommended_tracks', models.TextField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.userinfor')),
            ],
        ),
    ]
