# Generated by Django 5.0.4 on 2024-05-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_playlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='recommended_tracks',
            new_name='recommended_track_ids',
        ),
        migrations.AddField(
            model_name='playlist',
            name='image_url',
            field=models.TextField(default='default_image_url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='total_duration',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
